### ISSUE TITLE
Share same WebGL context if you have multiple elements on the same page

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/immersive-custom-elements#39]
As `model-viewer` is currently doing, so you don't run out of gl context if your website has a many elements

**Comment by takahirox** [comment]
Probably we can use the same approach they do

https://github.com/GoogleWebComponents/model-viewer/issues/10#issuecomment-431204994
https://threejs.org/examples/?q=grid#webgl_multiple_canvases_grid

That is each element has a 2d context and drawing a single webgl context to canvases with 2d context .drawImage(). Maybe something like this

```javascript
const renderAll = () => {
    for (const element of elements) {
        const scene = element.scene;
        const camera = element.camera;
        const context = element.context; // CanvasRenderingContext2D of each element
        renderer.render(scene, camera);
        context.drawImage(renderer.domElement, 0, 0);
    }
};
```

**Comment by DavidPeicho** [comment]
Be careful though `context.drawImage`. I encountered a problem just today with that technique. The browser can basically clears the compositing result in between the WebGL rendering and the `drawImage` call.

```javascript
const myWebGLCanvas = ...;
const context = document.createElement('canvas').getContext('2d');

// Draws stuff to `myWebGLCanvas` using WebGL.
render();
// Blits to the 2d context.
context.drawImage(myWebGLCanvas, 0, 0);

// Oops! This is empty :(
const pixels = ctx.getImageData(...).data;
```

If you want it to work as expected, you will need to use the `preserveDrawingBuffer` option on the WebGL context.

The WebGL specs states:
> This default behavior can be changed by setting the preserveDrawingBuffer attribute of the WebGLContextAttributes object. If this flag is true, the contents of the drawing buffer shall be preserved until the author either clears or overwrites them. If this flag is false, attempting to perform operations using this context as a source image after the rendering function has returned can lead to undefined behavior. This includes readPixels or toDataURL calls, using this context as the source image of another context's texImage2D or drawImage call, or creating an ImageBitmap [HTML] from this context's canvas.

I discovered that during testing, but I haven't seen any issues before that, and it's been month I am using this technique.

**Comment by takahirox** [comment]
Thanks for the comment! Let me look into in the detail later, I'm a bit too busy for other works now...
