### ISSUE TITLE
Implement <custom-shader>

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/immersive-custom-elements#6]
Prototype https://twitter.com/superhoge/status/1132343604352049152

**Comment by joshmarinacci** [comment]
This would be super fun. It feels very open ended though. What is the shader used for? Replacing a background image for the whole page? Creating a div that you click on for immersive mode?

**Comment by takahirox** [comment]
This project is for immersive experience so currently I'm thinking of the latter one.

> Creating a div that you click on for immersive mode?

But I'm not sure yet if seeing it in VR mode looks nice. I think I need some experiments to find the best use cases.

**Comment by joshmarinacci** [comment]
I agree.  Without depth control I'm not sure what you'd use it for in VR. Is it possible to nest elements? ex: 

```
<immersive-cube>
   <custom-shader>
```

so that you could use the shader on an object?
