### ISSUE TITLE
Make dev branch

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/immersive-custom-elements#61]
Currently we have only master branch, and we provide demo as GitHub page. In this structure, GitHub page always refers to the master branch including the newest code. But the newest code can be sometimes buggy for example if we add big change. So having dev and master branches may be safer, dev includes the newest code and master includes the latest released code.

**Comment by takahirox** [comment]
I've made dev branch.

@fernandojsg Would you switch the default branch to dev via "settings" or give a permission to me? "settings" doesn't appear on my side.

**Comment by joshmarinacci** [comment]
bump

**Comment by joshmarinacci** [comment]
You should have access now @takahirox

**Comment by takahirox** [comment]
I still don't see

![image](https://user-images.githubusercontent.com/7637832/69190697-cbb26780-0ad5-11ea-87c3-be2faeba30b7.png)

**Comment by joshmarinacci** [comment]
can you try now?

**Comment by takahirox** [comment]
I see now. And I changed, thanks!
