### ISSUE TITLE
<img-360> can't enter fullscreen mode on iPhone/iPod touch

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/immersive-custom-elements#67]
From #60

On iOS (my iPod touch) + Safari, \<img-360\> can't enter fullscreen mode. I haven't checked any console errors yet.

**Comment by takahirox** [comment]
I don't have platform where I can debug on iOS. I need help.

**Comment by takahirox** [comment]
I can reproduce this problem even on iOS + Chrome. Maybe (mobile?) iOS specific issue regardless of browsers.

**Comment by takahirox** [comment]
I can reproduce this problem on iPad + Safari.

**Comment by psimyn** [comment]
I tested in BrowserStack (iPad with Safari), got this error when clicking:

```
TypeError: document.exitFullscreen is not a function. (In 'document.exitFullscreen()', 'document.exitFullscreen' is undefined)(anonymous function) @ immersive-custom-elements.js:49600
```

[here's the click handler](https://github.com/MozillaReality/immersive-custom-elements/blob/baeb5cd3bb73ba5a3274418edafd89284fe0969b/src/utils/vr-helper.js#L52) code that is breaking:

```
if (document.fullscreenElement === null) {
  canvas.requestFullscreen();
} else {
  document.exitFullscreen();
}
```

I think all the fullscreen things need `webkit` prefix or a polyfill

**Comment by takahirox** [comment]
Screenshot of iPad + Safari. It enters fullscreen mode but image (dom element) isn't resized. 

![IMG_0249](https://user-images.githubusercontent.com/7637832/63734251-712eb400-c8b6-11e9-9f29-b5f239a85be8.jpg)

iPad + Chrome doesn't seem to support Fullscreen API.

The results are the same as the [screenfull.js demo](https://sindresorhus.com/screenfull.js/) so probably these behaviors are the intentional. So closing this issue.

**Comment by fernandojsg** [comment]
Out of curiosity, have you tried <model-viewer> to see if they have the same issue?

**Comment by takahirox** [comment]
Who are "they" in this case? screenfull.js?

**Comment by fernandojsg** [comment]
Ops I used `<model-viewer>` without escaping the tags and it was just hidden :D.
I mean if modelviewer has the same issues on ipad/iphone with the fullscreen or they have another solution

**Comment by takahirox** [comment]
OK, let me try at home tonight. I don't have iPad at the office.
