### ISSUE TITLE
2D canvas component

### ISSUE THREAD

**Issue by joshmarinacci** [MozillaReality/immersive-custom-elements#73]
We should have a component that takes an existing 2D canvas game and projects it into 3d space. At first it should look just like the 2d canvas on the page, but gives you an overlay to enter immersive mode. Then it handles copying content from the canvas to a 3d texture of the correct size and position, and sends emulated mouse events from the immersive controller.  It would also let you customize the background when in 3D.

**Comment by blairmacintyre** [comment]
Why just a canvas?  Perhaps thinking about any DOM element (via https://github.com/aelatgt/three-web-layer) and doing some smart things with placement and interaction, would be more interesting / generically useful?
