### ISSUE TITLE
New custom element idea brainstorming thread

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/immersive-custom-elements#9]
Brainstorming thread. Feel free to write anything about new custom elements ideas. I open an individual issue "implement \<xxx-yyy\>" if the idea looks nice to go.

**Comment by joshmarinacci** [comment]
is model viewer still on our roadmap?

**Comment by takahirox** [comment]
Personally no unless Google gives up supporting VR mode in their \<model-viewer\>.

**Comment by blairmacintyre** [comment]
I would like to see us do something like a <immersive-scene> where the scene is defined in three.js.  Think of it akin to something like <a-scene> but without any of the aframe baggage.  Essentially, what this would do is:
- handle the mechanics of multiple "3D, could be immersive" entities on a single page
- have options for what goes in the flat page element, and what scenes to show for AR or VR
- assist with dealing with some of the progressive refinement details.

I'm motivated here looking at the way the NYTimes implements their interactive pages.  They create DOM elements for the various sorts of scenes (be in SVG animations controlled by page scroll, or AR content for the mobile app) but the content of the scenes is largely custom-per-page (obviously some is generated by their tools, but the stuff that is generated ends up being "custom" for that page)

I'm also motivated by this being the "low bar for a framework that simplifies targeting different platforms sensibly"

I'm discussing how to make our "AR VR immersive book" (with my co-authors) and I'd love to explore this approach vs AFrame.

**Comment by joshmarinacci** [comment]
I'll make a new issue for this. I agree with you.

**Comment by pryan1068** [comment]
Not sure if this is best place for this but will try. Let me know if not.

Geo-Registered 360 Video
Looking for ability to render geo-tags over top of live 360 camera feed. Navigation aids (routes, arrows, breadcrumbs, etc.), points of interest (people, places, things), cities publish sewage and buried lines locations so we can see them in our yards, etc. Mozilla looking very attractive for this.

Maybe 360 video can be the background and then overlay openlayers or cesiumjs over top of it? And geo-ref the two together so they match. The more precise and accurate they are, the more opportunities that will arise.

I think the speed and ease at which we could then create geo-registered AR and VR would attract a lot of players. Mozilla in automated car dash displays. See-thru the airplane walls during your flight.
